export const SET_USERNAME = "SET_USERNAME";
export const SET_ACCOUNT_ID= "SET_ACCOUNT_ID"
export const SET_GAMES_LIST = "SET_GAMES_LIST";
export const UPDATE_GAMES_LIST = "UPDATE_GAMES_LIST"
export const SET_GAME_DETAILS = "SET_GAME_DETAILS"

