const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const detailsSchema = new Schema({
    gameId: { type: Number },
    platformId: { type: String },
    gameCreation: { type: Number },
    gameDuration: { type: Number },
    queueId: { type: Number },
    mapId: { type: Number },
    seasonId: { type: Number },
    gameVersion: { type: String },
    gameMode: { type: String },
    gameType: { type: String },
    teams: [{
        teamId: { type: Number },
        win: { type: String },
        firstBlood: { type: Boolean },
        firstTower: { type: Boolean },
        firstInhibitor: { type: Boolean },
        firstBaron: { type: Boolean },
        firstDragon: { type: Boolean },
        firstRiftHerald: { type: Boolean },
        towerKills: { type: Number },
        inhibitorKills: { type: Number },
        baronKills: { type: Number },
        dragonKills: { type: Number },
        vilemawKills: { type: Number },
        riftHeraldKills: { type: Number },
        dominionVictoryScore: { type: Number },
        bans: [
            {
                championId: { type: Number },
                pickTurn: { type: Number },
            },
            {
                championId: { type: Number },
                pickTurn: { type: Number },
            },
            {
                championId: { type: Number },
                pickTurn: { type: Number },
            },
            {
                championId: { type: Number },
                pickTurn: { type: Number },
            },
            {
                championId: { type: Number },
                pickTurn: { type: Number },
            }
        ]
    },
    {
        teamId: { type: Number },
        win: { type: String },
        firstBlood: { type: Boolean },
        firstTower: { type: Boolean },
        firstInhibitor: { type: Boolean },
        firstBaron: { type: Boolean },
        firstDragon: { type: Boolean },
        firstRiftHerald: { type: Boolean },
        towerKills: { type: Number },
        inhibitorKills: { type: Number },
        baronKills: { type: Number },
        dragonKills: { type: Number },
        vilemawKills: { type: Number },
        riftHeraldKills: { type: Number },
        dominionVictoryScore: { type: Number },
        bans: [
            {
                championId: { type: Number },
                pickTurn: { type: Number },
            },
            {
                championId: { type: Number },
                pickTurn: { type: Number },
            },
            {
                championId: { type: Number },
                pickTurn: { type: Number },
            },
            {
                championId: { type: Number },
                pickTurn: { type: Number },
            },
            {
                championId: { type: Number },
                pickTurn: { type: Number },
            }
        ]
    }],
    participants: [
        {
        "participantId": { type: Number },
        "teamId": { type: Number },
        "championId": { type: Number },
        "spell1Id": { type: Number },
        "spell2Id": { type: Number },
        "stats": {
          "participantId": { type: Number },
          "win": { type: Boolean },
          "item0": { type: Number },
          "item1": { type: Number },
          "item2": { type: Number },
          "item3": { type: Number },
          "item4": { type: Number },
          "item5": { type: Number },
          "item6": { type: Number },
          "kills": { type: Number },
          "deaths": { type: Number },
          "assists": { type: Number },
          "largestKillingSpree": { type: Number },
          "largestMultiKill": { type: Number },
          "killingSprees": { type: Number },
          "longestTimeSpentLiving": { type: Number },
          "doubleKills": { type: Number },
          "tripleKills": { type: Number },
          "quadraKills": { type: Number },
          "pentaKills": { type: Number },
          "unrealKills": { type: Number },
          "totalDamageDealt": { type: Number },
          "magicDamageDealt": { type: Number },
          "physicalDamageDealt": { type: Number },
          "trueDamageDealt": { type: Number },
          "largestCriticalStrike": { type: Number },
          "totalDamageDealtToChampions": { type: Number },
          "magicDamageDealtToChampions": { type: Number },
          "physicalDamageDealtToChampions": { type: Number },
          "trueDamageDealtToChampions": { type: Number },
          "totalHeal": { type: Number },
          "totalUnitsHealed": { type: Number },
          "damageSelfMitigated": { type: Number },
          "damageDealtToObjectives": { type: Number },
          "damageDealtToTurrets": { type: Number },
          "visionScore": { type: Number },
          "timeCCingOthers": { type: Number },
          "totalDamageTaken": { type: Number },
          "magicalDamageTaken": { type: Number },
          "physicalDamageTaken": { type: Number },
          "trueDamageTaken": { type: Number },
          "goldEarned": { type: Number },
          "goldSpent": { type: Number },
          "turretKills": { type: Number },
          "inhibitorKills": { type: Number },
          "totalMinionsKilled": { type: Number },
          "neutralMinionsKilled": { type: Number },
          "neutralMinionsKilledTeamJungle": { type: Number },
          "neutralMinionsKilledEnemyJungle": { type: Number },
          "totalTimeCrowdControlDealt": { type: Number },
          "champLevel": { type: Number },
          "visionWardsBoughtInGame": { type: Number },
          "sightWardsBoughtInGame": { type: Number },
          "wardsPlaced": { type: Number },
          "wardsKilled": { type: Number },
          "firstBloodKill": { type: Boolean },
          "firstBloodAssist": { type: Boolean },
          "firstTowerKill": { type: Boolean },
          "firstTowerAssist": { type: Boolean },
          "firstInhibitorKill": { type: Boolean },
          "firstInhibitorAssist": { type: Boolean },
          "combatPlayerScore": { type: Number },
          "objectivePlayerScore": { type: Number },
          "totalPlayerScore": { type: Number },
          "totalScoreRank": { type: Number },
          "playerScore0": { type: Number },
          "playerScore1": { type: Number },
          "playerScore2": { type: Number },
          "playerScore3": { type: Number },
          "playerScore4": { type: Number },
          "playerScore5": { type: Number },
          "playerScore6": { type: Number },
          "playerScore7": { type: Number },
          "playerScore8": { type: Number },
          "playerScore9": { type: Number },
          "perk0": { type: Number },
          "perk0Var1": { type: Number },
          "perk0Var2": { type: Number },
          "perk0Var3": { type: Number },
          "perk1": { type: Number },
          "perk1Var1": { type: Number },
          "perk1Var2": { type: Number },
          "perk1Var3": { type: Number },
          "perk2": { type: Number },
          "perk2Var1": { type: Number },
          "perk2Var2": { type: Number },
          "perk2Var3": { type: Number },
          "perk3": { type: Number },
          "perk3Var1": { type: Number },
          "perk3Var2": { type: Number },
          "perk3Var3": { type: Number },
          "perk4": { type: Number },
          "perk4Var1": { type: Number },
          "perk4Var2": { type: Number },
          "perk4Var3": { type: Number },
          "perk5": { type: Number },
          "perk5Var1": { type: Number },
          "perk5Var2": { type: Number },
          "perk5Var3": { type: Number },
          "perkPrimaryStyle": { type: Number },
          "perkSubStyle": { type: Number },
          "statPerk0": { type: Number },
          "statPerk1": { type: Number },
          "statPerk2": { type: Number }
        },
        // "timeline": {
        //   "participantId": { type: Number },
        //   "creepsPerMinDeltas": {
        //     "10-20": 3.2,
        //     "0-10": 5.3,
        //     "20-30": 2.0999999999999996
        //   },
        //   "xpPerMinDeltas": {
        //     "10-20": 520.1,
        //     "0-10": 381.29999999999995,
        //     "20-30": 482.09999999999997
        //   },
        //   "goldPerMinDeltas": {
        //     "10-20": 486.20000000000005,
        //     "0-10": 276,
        //     "20-30": 471.6
        //   },
        //   "csDiffPerMinDeltas": {
        //     "10-20": 0.9000000000000001,
        //     "0-10": 0.4999999999999998,
        //     "20-30": -1.5000000000000002
        //   },
        //   "xpDiffPerMinDeltas": {
        //     "10-20": 229.40000000000003,
        //     "0-10": -0.8000000000000114,
        //     "20-30": -27.500000000000057
        //   },
        //   "damageTakenPerMinDeltas": {
        //     "10-20": 1285.7,
        //     "0-10": 538,
        //     "20-30": 2024
        //   },
        //   "damageTakenDiffPerMinDeltas": {
        //     "10-20": 72.80000000000001,
        //     "0-10": 91.50000000000006,
        //     "20-30": 531.9
        //   },
        //   "role": "SOLO",
        //   "lane": "MIDDLE"
        // }
      },
      {
        "participantId": { type: Number },
        "teamId": { type: Number },
        "championId": { type: Number },
        "spell1Id": { type: Number },
        "spell2Id": { type: Number },
        "stats": {
          "participantId": { type: Number },
          "win": { type: Boolean },
          "item0": { type: Number },
          "item1": { type: Number },
          "item2": { type: Number },
          "item3": { type: Number },
          "item4": { type: Number },
          "item5": { type: Number },
          "item6": { type: Number },
          "kills": { type: Number },
          "deaths": { type: Number },
          "assists": { type: Number },
          "largestKillingSpree": { type: Number },
          "largestMultiKill": { type: Number },
          "killingSprees": { type: Number },
          "longestTimeSpentLiving": { type: Number },
          "doubleKills": { type: Number },
          "tripleKills": { type: Number },
          "quadraKills": { type: Number },
          "pentaKills": { type: Number },
          "unrealKills": { type: Number },
          "totalDamageDealt": { type: Number },
          "magicDamageDealt": { type: Number },
          "physicalDamageDealt": { type: Number },
          "trueDamageDealt": { type: Number },
          "largestCriticalStrike": { type: Number },
          "totalDamageDealtToChampions": { type: Number },
          "magicDamageDealtToChampions": { type: Number },
          "physicalDamageDealtToChampions": { type: Number },
          "trueDamageDealtToChampions": { type: Number },
          "totalHeal": { type: Number },
          "totalUnitsHealed": { type: Number },
          "damageSelfMitigated": { type: Number },
          "damageDealtToObjectives": { type: Number },
          "damageDealtToTurrets": { type: Number },
          "visionScore": { type: Number },
          "timeCCingOthers": { type: Number },
          "totalDamageTaken": { type: Number },
          "magicalDamageTaken": { type: Number },
          "physicalDamageTaken": { type: Number },
          "trueDamageTaken": { type: Number },
          "goldEarned": { type: Number },
          "goldSpent": { type: Number },
          "turretKills": { type: Number },
          "inhibitorKills": { type: Number },
          "totalMinionsKilled": { type: Number },
          "neutralMinionsKilled": { type: Number },
          "neutralMinionsKilledTeamJungle": { type: Number },
          "neutralMinionsKilledEnemyJungle": { type: Number },
          "totalTimeCrowdControlDealt": { type: Number },
          "champLevel": { type: Number },
          "visionWardsBoughtInGame": { type: Number },
          "sightWardsBoughtInGame": { type: Number },
          "wardsPlaced": { type: Number },
          "wardsKilled": { type: Number },
          "firstBloodKill": { type: Boolean },
          "firstBloodAssist": { type: Boolean },
          "firstTowerKill": { type: Boolean },
          "firstTowerAssist": { type: Boolean },
          "firstInhibitorKill": { type: Boolean },
          "firstInhibitorAssist": { type: Boolean },
          "combatPlayerScore": { type: Number },
          "objectivePlayerScore": { type: Number },
          "totalPlayerScore": { type: Number },
          "totalScoreRank": { type: Number },
          "playerScore0": { type: Number },
          "playerScore1": { type: Number },
          "playerScore2": { type: Number },
          "playerScore3": { type: Number },
          "playerScore4": { type: Number },
          "playerScore5": { type: Number },
          "playerScore6": { type: Number },
          "playerScore7": { type: Number },
          "playerScore8": { type: Number },
          "playerScore9": { type: Number },
          "perk0": { type: Number },
          "perk0Var1": { type: Number },
          "perk0Var2": { type: Number },
          "perk0Var3": { type: Number },
          "perk1": { type: Number },
          "perk1Var1": { type: Number },
          "perk1Var2": { type: Number },
          "perk1Var3": { type: Number },
          "perk2": { type: Number },
          "perk2Var1": { type: Number },
          "perk2Var2": { type: Number },
          "perk2Var3": { type: Number },
          "perk3": { type: Number },
          "perk3Var1": { type: Number },
          "perk3Var2": { type: Number },
          "perk3Var3": { type: Number },
          "perk4": { type: Number },
          "perk4Var1": { type: Number },
          "perk4Var2": { type: Number },
          "perk4Var3": { type: Number },
          "perk5": { type: Number },
          "perk5Var1": { type: Number },
          "perk5Var2": { type: Number },
          "perk5Var3": { type: Number },
          "perkPrimaryStyle": { type: Number },
          "perkSubStyle": { type: Number },
          "statPerk0": { type: Number },
          "statPerk1": { type: Number },
          "statPerk2": { type: Number }
        },
        // "timeline": {
        //   "participantId": { type: Number },
        //   "creepsPerMinDeltas": {
        //     "10-20": 3.2,
        //     "0-10": 5.3,
        //     "20-30": 2.0999999999999996
        //   },
        //   "xpPerMinDeltas": {
        //     "10-20": 520.1,
        //     "0-10": 381.29999999999995,
        //     "20-30": 482.09999999999997
        //   },
        //   "goldPerMinDeltas": {
        //     "10-20": 486.20000000000005,
        //     "0-10": 276,
        //     "20-30": 471.6
        //   },
        //   "csDiffPerMinDeltas": {
        //     "10-20": 0.9000000000000001,
        //     "0-10": 0.4999999999999998,
        //     "20-30": -1.5000000000000002
        //   },
        //   "xpDiffPerMinDeltas": {
        //     "10-20": 229.40000000000003,
        //     "0-10": -0.8000000000000114,
        //     "20-30": -27.500000000000057
        //   },
        //   "damageTakenPerMinDeltas": {
        //     "10-20": 1285.7,
        //     "0-10": 538,
        //     "20-30": 2024
        //   },
        //   "damageTakenDiffPerMinDeltas": {
        //     "10-20": 72.80000000000001,
        //     "0-10": 91.50000000000006,
        //     "20-30": 531.9
        //   },
        //   "role": "SOLO",
        //   "lane": "MIDDLE"
        // }
      },{
        "participantId": { type: Number },
        "teamId": { type: Number },
        "championId": { type: Number },
        "spell1Id": { type: Number },
        "spell2Id": { type: Number },
        "stats": {
          "participantId": { type: Number },
          "win": { type: Boolean },
          "item0": { type: Number },
          "item1": { type: Number },
          "item2": { type: Number },
          "item3": { type: Number },
          "item4": { type: Number },
          "item5": { type: Number },
          "item6": { type: Number },
          "kills": { type: Number },
          "deaths": { type: Number },
          "assists": { type: Number },
          "largestKillingSpree": { type: Number },
          "largestMultiKill": { type: Number },
          "killingSprees": { type: Number },
          "longestTimeSpentLiving": { type: Number },
          "doubleKills": { type: Number },
          "tripleKills": { type: Number },
          "quadraKills": { type: Number },
          "pentaKills": { type: Number },
          "unrealKills": { type: Number },
          "totalDamageDealt": { type: Number },
          "magicDamageDealt": { type: Number },
          "physicalDamageDealt": { type: Number },
          "trueDamageDealt": { type: Number },
          "largestCriticalStrike": { type: Number },
          "totalDamageDealtToChampions": { type: Number },
          "magicDamageDealtToChampions": { type: Number },
          "physicalDamageDealtToChampions": { type: Number },
          "trueDamageDealtToChampions": { type: Number },
          "totalHeal": { type: Number },
          "totalUnitsHealed": { type: Number },
          "damageSelfMitigated": { type: Number },
          "damageDealtToObjectives": { type: Number },
          "damageDealtToTurrets": { type: Number },
          "visionScore": { type: Number },
          "timeCCingOthers": { type: Number },
          "totalDamageTaken": { type: Number },
          "magicalDamageTaken": { type: Number },
          "physicalDamageTaken": { type: Number },
          "trueDamageTaken": { type: Number },
          "goldEarned": { type: Number },
          "goldSpent": { type: Number },
          "turretKills": { type: Number },
          "inhibitorKills": { type: Number },
          "totalMinionsKilled": { type: Number },
          "neutralMinionsKilled": { type: Number },
          "neutralMinionsKilledTeamJungle": { type: Number },
          "neutralMinionsKilledEnemyJungle": { type: Number },
          "totalTimeCrowdControlDealt": { type: Number },
          "champLevel": { type: Number },
          "visionWardsBoughtInGame": { type: Number },
          "sightWardsBoughtInGame": { type: Number },
          "wardsPlaced": { type: Number },
          "wardsKilled": { type: Number },
          "firstBloodKill": { type: Boolean },
          "firstBloodAssist": { type: Boolean },
          "firstTowerKill": { type: Boolean },
          "firstTowerAssist": { type: Boolean },
          "firstInhibitorKill": { type: Boolean },
          "firstInhibitorAssist": { type: Boolean },
          "combatPlayerScore": { type: Number },
          "objectivePlayerScore": { type: Number },
          "totalPlayerScore": { type: Number },
          "totalScoreRank": { type: Number },
          "playerScore0": { type: Number },
          "playerScore1": { type: Number },
          "playerScore2": { type: Number },
          "playerScore3": { type: Number },
          "playerScore4": { type: Number },
          "playerScore5": { type: Number },
          "playerScore6": { type: Number },
          "playerScore7": { type: Number },
          "playerScore8": { type: Number },
          "playerScore9": { type: Number },
          "perk0": { type: Number },
          "perk0Var1": { type: Number },
          "perk0Var2": { type: Number },
          "perk0Var3": { type: Number },
          "perk1": { type: Number },
          "perk1Var1": { type: Number },
          "perk1Var2": { type: Number },
          "perk1Var3": { type: Number },
          "perk2": { type: Number },
          "perk2Var1": { type: Number },
          "perk2Var2": { type: Number },
          "perk2Var3": { type: Number },
          "perk3": { type: Number },
          "perk3Var1": { type: Number },
          "perk3Var2": { type: Number },
          "perk3Var3": { type: Number },
          "perk4": { type: Number },
          "perk4Var1": { type: Number },
          "perk4Var2": { type: Number },
          "perk4Var3": { type: Number },
          "perk5": { type: Number },
          "perk5Var1": { type: Number },
          "perk5Var2": { type: Number },
          "perk5Var3": { type: Number },
          "perkPrimaryStyle": { type: Number },
          "perkSubStyle": { type: Number },
          "statPerk0": { type: Number },
          "statPerk1": { type: Number },
          "statPerk2": { type: Number }
        },
        // "timeline": {
        //   "participantId": { type: Number },
        //   "creepsPerMinDeltas": {
        //     "10-20": 3.2,
        //     "0-10": 5.3,
        //     "20-30": 2.0999999999999996
        //   },
        //   "xpPerMinDeltas": {
        //     "10-20": 520.1,
        //     "0-10": 381.29999999999995,
        //     "20-30": 482.09999999999997
        //   },
        //   "goldPerMinDeltas": {
        //     "10-20": 486.20000000000005,
        //     "0-10": 276,
        //     "20-30": 471.6
        //   },
        //   "csDiffPerMinDeltas": {
        //     "10-20": 0.9000000000000001,
        //     "0-10": 0.4999999999999998,
        //     "20-30": -1.5000000000000002
        //   },
        //   "xpDiffPerMinDeltas": {
        //     "10-20": 229.40000000000003,
        //     "0-10": -0.8000000000000114,
        //     "20-30": -27.500000000000057
        //   },
        //   "damageTakenPerMinDeltas": {
        //     "10-20": 1285.7,
        //     "0-10": 538,
        //     "20-30": 2024
        //   },
        //   "damageTakenDiffPerMinDeltas": {
        //     "10-20": 72.80000000000001,
        //     "0-10": 91.50000000000006,
        //     "20-30": 531.9
        //   },
        //   "role": "SOLO",
        //   "lane": "MIDDLE"
        // }
      },{
        "participantId": { type: Number },
        "teamId": { type: Number },
        "championId": { type: Number },
        "spell1Id": { type: Number },
        "spell2Id": { type: Number },
        "stats": {
          "participantId": { type: Number },
          "win": { type: Boolean },
          "item0": { type: Number },
          "item1": { type: Number },
          "item2": { type: Number },
          "item3": { type: Number },
          "item4": { type: Number },
          "item5": { type: Number },
          "item6": { type: Number },
          "kills": { type: Number },
          "deaths": { type: Number },
          "assists": { type: Number },
          "largestKillingSpree": { type: Number },
          "largestMultiKill": { type: Number },
          "killingSprees": { type: Number },
          "longestTimeSpentLiving": { type: Number },
          "doubleKills": { type: Number },
          "tripleKills": { type: Number },
          "quadraKills": { type: Number },
          "pentaKills": { type: Number },
          "unrealKills": { type: Number },
          "totalDamageDealt": { type: Number },
          "magicDamageDealt": { type: Number },
          "physicalDamageDealt": { type: Number },
          "trueDamageDealt": { type: Number },
          "largestCriticalStrike": { type: Number },
          "totalDamageDealtToChampions": { type: Number },
          "magicDamageDealtToChampions": { type: Number },
          "physicalDamageDealtToChampions": { type: Number },
          "trueDamageDealtToChampions": { type: Number },
          "totalHeal": { type: Number },
          "totalUnitsHealed": { type: Number },
          "damageSelfMitigated": { type: Number },
          "damageDealtToObjectives": { type: Number },
          "damageDealtToTurrets": { type: Number },
          "visionScore": { type: Number },
          "timeCCingOthers": { type: Number },
          "totalDamageTaken": { type: Number },
          "magicalDamageTaken": { type: Number },
          "physicalDamageTaken": { type: Number },
          "trueDamageTaken": { type: Number },
          "goldEarned": { type: Number },
          "goldSpent": { type: Number },
          "turretKills": { type: Number },
          "inhibitorKills": { type: Number },
          "totalMinionsKilled": { type: Number },
          "neutralMinionsKilled": { type: Number },
          "neutralMinionsKilledTeamJungle": { type: Number },
          "neutralMinionsKilledEnemyJungle": { type: Number },
          "totalTimeCrowdControlDealt": { type: Number },
          "champLevel": { type: Number },
          "visionWardsBoughtInGame": { type: Number },
          "sightWardsBoughtInGame": { type: Number },
          "wardsPlaced": { type: Number },
          "wardsKilled": { type: Number },
          "firstBloodKill": { type: Boolean },
          "firstBloodAssist": { type: Boolean },
          "firstTowerKill": { type: Boolean },
          "firstTowerAssist": { type: Boolean },
          "firstInhibitorKill": { type: Boolean },
          "firstInhibitorAssist": { type: Boolean },
          "combatPlayerScore": { type: Number },
          "objectivePlayerScore": { type: Number },
          "totalPlayerScore": { type: Number },
          "totalScoreRank": { type: Number },
          "playerScore0": { type: Number },
          "playerScore1": { type: Number },
          "playerScore2": { type: Number },
          "playerScore3": { type: Number },
          "playerScore4": { type: Number },
          "playerScore5": { type: Number },
          "playerScore6": { type: Number },
          "playerScore7": { type: Number },
          "playerScore8": { type: Number },
          "playerScore9": { type: Number },
          "perk0": { type: Number },
          "perk0Var1": { type: Number },
          "perk0Var2": { type: Number },
          "perk0Var3": { type: Number },
          "perk1": { type: Number },
          "perk1Var1": { type: Number },
          "perk1Var2": { type: Number },
          "perk1Var3": { type: Number },
          "perk2": { type: Number },
          "perk2Var1": { type: Number },
          "perk2Var2": { type: Number },
          "perk2Var3": { type: Number },
          "perk3": { type: Number },
          "perk3Var1": { type: Number },
          "perk3Var2": { type: Number },
          "perk3Var3": { type: Number },
          "perk4": { type: Number },
          "perk4Var1": { type: Number },
          "perk4Var2": { type: Number },
          "perk4Var3": { type: Number },
          "perk5": { type: Number },
          "perk5Var1": { type: Number },
          "perk5Var2": { type: Number },
          "perk5Var3": { type: Number },
          "perkPrimaryStyle": { type: Number },
          "perkSubStyle": { type: Number },
          "statPerk0": { type: Number },
          "statPerk1": { type: Number },
          "statPerk2": { type: Number }
        },
        // "timeline": {
        //   "participantId": { type: Number },
        //   "creepsPerMinDeltas": {
        //     "10-20": 3.2,
        //     "0-10": 5.3,
        //     "20-30": 2.0999999999999996
        //   },
        //   "xpPerMinDeltas": {
        //     "10-20": 520.1,
        //     "0-10": 381.29999999999995,
        //     "20-30": 482.09999999999997
        //   },
        //   "goldPerMinDeltas": {
        //     "10-20": 486.20000000000005,
        //     "0-10": 276,
        //     "20-30": 471.6
        //   },
        //   "csDiffPerMinDeltas": {
        //     "10-20": 0.9000000000000001,
        //     "0-10": 0.4999999999999998,
        //     "20-30": -1.5000000000000002
        //   },
        //   "xpDiffPerMinDeltas": {
        //     "10-20": 229.40000000000003,
        //     "0-10": -0.8000000000000114,
        //     "20-30": -27.500000000000057
        //   },
        //   "damageTakenPerMinDeltas": {
        //     "10-20": 1285.7,
        //     "0-10": 538,
        //     "20-30": 2024
        //   },
        //   "damageTakenDiffPerMinDeltas": {
        //     "10-20": 72.80000000000001,
        //     "0-10": 91.50000000000006,
        //     "20-30": 531.9
        //   },
        //   "role": "SOLO",
        //   "lane": "MIDDLE"
        // }
      },{
        "participantId": { type: Number },
        "teamId": { type: Number },
        "championId": { type: Number },
        "spell1Id": { type: Number },
        "spell2Id": { type: Number },
        "stats": {
          "participantId": { type: Number },
          "win": { type: Boolean },
          "item0": { type: Number },
          "item1": { type: Number },
          "item2": { type: Number },
          "item3": { type: Number },
          "item4": { type: Number },
          "item5": { type: Number },
          "item6": { type: Number },
          "kills": { type: Number },
          "deaths": { type: Number },
          "assists": { type: Number },
          "largestKillingSpree": { type: Number },
          "largestMultiKill": { type: Number },
          "killingSprees": { type: Number },
          "longestTimeSpentLiving": { type: Number },
          "doubleKills": { type: Number },
          "tripleKills": { type: Number },
          "quadraKills": { type: Number },
          "pentaKills": { type: Number },
          "unrealKills": { type: Number },
          "totalDamageDealt": { type: Number },
          "magicDamageDealt": { type: Number },
          "physicalDamageDealt": { type: Number },
          "trueDamageDealt": { type: Number },
          "largestCriticalStrike": { type: Number },
          "totalDamageDealtToChampions": { type: Number },
          "magicDamageDealtToChampions": { type: Number },
          "physicalDamageDealtToChampions": { type: Number },
          "trueDamageDealtToChampions": { type: Number },
          "totalHeal": { type: Number },
          "totalUnitsHealed": { type: Number },
          "damageSelfMitigated": { type: Number },
          "damageDealtToObjectives": { type: Number },
          "damageDealtToTurrets": { type: Number },
          "visionScore": { type: Number },
          "timeCCingOthers": { type: Number },
          "totalDamageTaken": { type: Number },
          "magicalDamageTaken": { type: Number },
          "physicalDamageTaken": { type: Number },
          "trueDamageTaken": { type: Number },
          "goldEarned": { type: Number },
          "goldSpent": { type: Number },
          "turretKills": { type: Number },
          "inhibitorKills": { type: Number },
          "totalMinionsKilled": { type: Number },
          "neutralMinionsKilled": { type: Number },
          "neutralMinionsKilledTeamJungle": { type: Number },
          "neutralMinionsKilledEnemyJungle": { type: Number },
          "totalTimeCrowdControlDealt": { type: Number },
          "champLevel": { type: Number },
          "visionWardsBoughtInGame": { type: Number },
          "sightWardsBoughtInGame": { type: Number },
          "wardsPlaced": { type: Number },
          "wardsKilled": { type: Number },
          "firstBloodKill": { type: Boolean },
          "firstBloodAssist": { type: Boolean },
          "firstTowerKill": { type: Boolean },
          "firstTowerAssist": { type: Boolean },
          "firstInhibitorKill": { type: Boolean },
          "firstInhibitorAssist": { type: Boolean },
          "combatPlayerScore": { type: Number },
          "objectivePlayerScore": { type: Number },
          "totalPlayerScore": { type: Number },
          "totalScoreRank": { type: Number },
          "playerScore0": { type: Number },
          "playerScore1": { type: Number },
          "playerScore2": { type: Number },
          "playerScore3": { type: Number },
          "playerScore4": { type: Number },
          "playerScore5": { type: Number },
          "playerScore6": { type: Number },
          "playerScore7": { type: Number },
          "playerScore8": { type: Number },
          "playerScore9": { type: Number },
          "perk0": { type: Number },
          "perk0Var1": { type: Number },
          "perk0Var2": { type: Number },
          "perk0Var3": { type: Number },
          "perk1": { type: Number },
          "perk1Var1": { type: Number },
          "perk1Var2": { type: Number },
          "perk1Var3": { type: Number },
          "perk2": { type: Number },
          "perk2Var1": { type: Number },
          "perk2Var2": { type: Number },
          "perk2Var3": { type: Number },
          "perk3": { type: Number },
          "perk3Var1": { type: Number },
          "perk3Var2": { type: Number },
          "perk3Var3": { type: Number },
          "perk4": { type: Number },
          "perk4Var1": { type: Number },
          "perk4Var2": { type: Number },
          "perk4Var3": { type: Number },
          "perk5": { type: Number },
          "perk5Var1": { type: Number },
          "perk5Var2": { type: Number },
          "perk5Var3": { type: Number },
          "perkPrimaryStyle": { type: Number },
          "perkSubStyle": { type: Number },
          "statPerk0": { type: Number },
          "statPerk1": { type: Number },
          "statPerk2": { type: Number }
        },
        // "timeline": {
        //   "participantId": { type: Number },
        //   "creepsPerMinDeltas": {
        //     "10-20": 3.2,
        //     "0-10": 5.3,
        //     "20-30": 2.0999999999999996
        //   },
        //   "xpPerMinDeltas": {
        //     "10-20": 520.1,
        //     "0-10": 381.29999999999995,
        //     "20-30": 482.09999999999997
        //   },
        //   "goldPerMinDeltas": {
        //     "10-20": 486.20000000000005,
        //     "0-10": 276,
        //     "20-30": 471.6
        //   },
        //   "csDiffPerMinDeltas": {
        //     "10-20": 0.9000000000000001,
        //     "0-10": 0.4999999999999998,
        //     "20-30": -1.5000000000000002
        //   },
        //   "xpDiffPerMinDeltas": {
        //     "10-20": 229.40000000000003,
        //     "0-10": -0.8000000000000114,
        //     "20-30": -27.500000000000057
        //   },
        //   "damageTakenPerMinDeltas": {
        //     "10-20": 1285.7,
        //     "0-10": 538,
        //     "20-30": 2024
        //   },
        //   "damageTakenDiffPerMinDeltas": {
        //     "10-20": 72.80000000000001,
        //     "0-10": 91.50000000000006,
        //     "20-30": 531.9
        //   },
        //   "role": "SOLO",
        //   "lane": "MIDDLE"
        // }
      },{
        "participantId": { type: Number },
        "teamId": { type: Number },
        "championId": { type: Number },
        "spell1Id": { type: Number },
        "spell2Id": { type: Number },
        "stats": {
          "participantId": { type: Number },
          "win": { type: Boolean },
          "item0": { type: Number },
          "item1": { type: Number },
          "item2": { type: Number },
          "item3": { type: Number },
          "item4": { type: Number },
          "item5": { type: Number },
          "item6": { type: Number },
          "kills": { type: Number },
          "deaths": { type: Number },
          "assists": { type: Number },
          "largestKillingSpree": { type: Number },
          "largestMultiKill": { type: Number },
          "killingSprees": { type: Number },
          "longestTimeSpentLiving": { type: Number },
          "doubleKills": { type: Number },
          "tripleKills": { type: Number },
          "quadraKills": { type: Number },
          "pentaKills": { type: Number },
          "unrealKills": { type: Number },
          "totalDamageDealt": { type: Number },
          "magicDamageDealt": { type: Number },
          "physicalDamageDealt": { type: Number },
          "trueDamageDealt": { type: Number },
          "largestCriticalStrike": { type: Number },
          "totalDamageDealtToChampions": { type: Number },
          "magicDamageDealtToChampions": { type: Number },
          "physicalDamageDealtToChampions": { type: Number },
          "trueDamageDealtToChampions": { type: Number },
          "totalHeal": { type: Number },
          "totalUnitsHealed": { type: Number },
          "damageSelfMitigated": { type: Number },
          "damageDealtToObjectives": { type: Number },
          "damageDealtToTurrets": { type: Number },
          "visionScore": { type: Number },
          "timeCCingOthers": { type: Number },
          "totalDamageTaken": { type: Number },
          "magicalDamageTaken": { type: Number },
          "physicalDamageTaken": { type: Number },
          "trueDamageTaken": { type: Number },
          "goldEarned": { type: Number },
          "goldSpent": { type: Number },
          "turretKills": { type: Number },
          "inhibitorKills": { type: Number },
          "totalMinionsKilled": { type: Number },
          "neutralMinionsKilled": { type: Number },
          "neutralMinionsKilledTeamJungle": { type: Number },
          "neutralMinionsKilledEnemyJungle": { type: Number },
          "totalTimeCrowdControlDealt": { type: Number },
          "champLevel": { type: Number },
          "visionWardsBoughtInGame": { type: Number },
          "sightWardsBoughtInGame": { type: Number },
          "wardsPlaced": { type: Number },
          "wardsKilled": { type: Number },
          "firstBloodKill": { type: Boolean },
          "firstBloodAssist": { type: Boolean },
          "firstTowerKill": { type: Boolean },
          "firstTowerAssist": { type: Boolean },
          "firstInhibitorKill": { type: Boolean },
          "firstInhibitorAssist": { type: Boolean },
          "combatPlayerScore": { type: Number },
          "objectivePlayerScore": { type: Number },
          "totalPlayerScore": { type: Number },
          "totalScoreRank": { type: Number },
          "playerScore0": { type: Number },
          "playerScore1": { type: Number },
          "playerScore2": { type: Number },
          "playerScore3": { type: Number },
          "playerScore4": { type: Number },
          "playerScore5": { type: Number },
          "playerScore6": { type: Number },
          "playerScore7": { type: Number },
          "playerScore8": { type: Number },
          "playerScore9": { type: Number },
          "perk0": { type: Number },
          "perk0Var1": { type: Number },
          "perk0Var2": { type: Number },
          "perk0Var3": { type: Number },
          "perk1": { type: Number },
          "perk1Var1": { type: Number },
          "perk1Var2": { type: Number },
          "perk1Var3": { type: Number },
          "perk2": { type: Number },
          "perk2Var1": { type: Number },
          "perk2Var2": { type: Number },
          "perk2Var3": { type: Number },
          "perk3": { type: Number },
          "perk3Var1": { type: Number },
          "perk3Var2": { type: Number },
          "perk3Var3": { type: Number },
          "perk4": { type: Number },
          "perk4Var1": { type: Number },
          "perk4Var2": { type: Number },
          "perk4Var3": { type: Number },
          "perk5": { type: Number },
          "perk5Var1": { type: Number },
          "perk5Var2": { type: Number },
          "perk5Var3": { type: Number },
          "perkPrimaryStyle": { type: Number },
          "perkSubStyle": { type: Number },
          "statPerk0": { type: Number },
          "statPerk1": { type: Number },
          "statPerk2": { type: Number }
        },
        // "timeline": {
        //   "participantId": { type: Number },
        //   "creepsPerMinDeltas": {
        //     "10-20": 3.2,
        //     "0-10": 5.3,
        //     "20-30": 2.0999999999999996
        //   },
        //   "xpPerMinDeltas": {
        //     "10-20": 520.1,
        //     "0-10": 381.29999999999995,
        //     "20-30": 482.09999999999997
        //   },
        //   "goldPerMinDeltas": {
        //     "10-20": 486.20000000000005,
        //     "0-10": 276,
        //     "20-30": 471.6
        //   },
        //   "csDiffPerMinDeltas": {
        //     "10-20": 0.9000000000000001,
        //     "0-10": 0.4999999999999998,
        //     "20-30": -1.5000000000000002
        //   },
        //   "xpDiffPerMinDeltas": {
        //     "10-20": 229.40000000000003,
        //     "0-10": -0.8000000000000114,
        //     "20-30": -27.500000000000057
        //   },
        //   "damageTakenPerMinDeltas": {
        //     "10-20": 1285.7,
        //     "0-10": 538,
        //     "20-30": 2024
        //   },
        //   "damageTakenDiffPerMinDeltas": {
        //     "10-20": 72.80000000000001,
        //     "0-10": 91.50000000000006,
        //     "20-30": 531.9
        //   },
        //   "role": "SOLO",
        //   "lane": "MIDDLE"
        // }
      },{
        "participantId": { type: Number },
        "teamId": { type: Number },
        "championId": { type: Number },
        "spell1Id": { type: Number },
        "spell2Id": { type: Number },
        "stats": {
          "participantId": { type: Number },
          "win": { type: Boolean },
          "item0": { type: Number },
          "item1": { type: Number },
          "item2": { type: Number },
          "item3": { type: Number },
          "item4": { type: Number },
          "item5": { type: Number },
          "item6": { type: Number },
          "kills": { type: Number },
          "deaths": { type: Number },
          "assists": { type: Number },
          "largestKillingSpree": { type: Number },
          "largestMultiKill": { type: Number },
          "killingSprees": { type: Number },
          "longestTimeSpentLiving": { type: Number },
          "doubleKills": { type: Number },
          "tripleKills": { type: Number },
          "quadraKills": { type: Number },
          "pentaKills": { type: Number },
          "unrealKills": { type: Number },
          "totalDamageDealt": { type: Number },
          "magicDamageDealt": { type: Number },
          "physicalDamageDealt": { type: Number },
          "trueDamageDealt": { type: Number },
          "largestCriticalStrike": { type: Number },
          "totalDamageDealtToChampions": { type: Number },
          "magicDamageDealtToChampions": { type: Number },
          "physicalDamageDealtToChampions": { type: Number },
          "trueDamageDealtToChampions": { type: Number },
          "totalHeal": { type: Number },
          "totalUnitsHealed": { type: Number },
          "damageSelfMitigated": { type: Number },
          "damageDealtToObjectives": { type: Number },
          "damageDealtToTurrets": { type: Number },
          "visionScore": { type: Number },
          "timeCCingOthers": { type: Number },
          "totalDamageTaken": { type: Number },
          "magicalDamageTaken": { type: Number },
          "physicalDamageTaken": { type: Number },
          "trueDamageTaken": { type: Number },
          "goldEarned": { type: Number },
          "goldSpent": { type: Number },
          "turretKills": { type: Number },
          "inhibitorKills": { type: Number },
          "totalMinionsKilled": { type: Number },
          "neutralMinionsKilled": { type: Number },
          "neutralMinionsKilledTeamJungle": { type: Number },
          "neutralMinionsKilledEnemyJungle": { type: Number },
          "totalTimeCrowdControlDealt": { type: Number },
          "champLevel": { type: Number },
          "visionWardsBoughtInGame": { type: Number },
          "sightWardsBoughtInGame": { type: Number },
          "wardsPlaced": { type: Number },
          "wardsKilled": { type: Number },
          "firstBloodKill": { type: Boolean },
          "firstBloodAssist": { type: Boolean },
          "firstTowerKill": { type: Boolean },
          "firstTowerAssist": { type: Boolean },
          "firstInhibitorKill": { type: Boolean },
          "firstInhibitorAssist": { type: Boolean },
          "combatPlayerScore": { type: Number },
          "objectivePlayerScore": { type: Number },
          "totalPlayerScore": { type: Number },
          "totalScoreRank": { type: Number },
          "playerScore0": { type: Number },
          "playerScore1": { type: Number },
          "playerScore2": { type: Number },
          "playerScore3": { type: Number },
          "playerScore4": { type: Number },
          "playerScore5": { type: Number },
          "playerScore6": { type: Number },
          "playerScore7": { type: Number },
          "playerScore8": { type: Number },
          "playerScore9": { type: Number },
          "perk0": { type: Number },
          "perk0Var1": { type: Number },
          "perk0Var2": { type: Number },
          "perk0Var3": { type: Number },
          "perk1": { type: Number },
          "perk1Var1": { type: Number },
          "perk1Var2": { type: Number },
          "perk1Var3": { type: Number },
          "perk2": { type: Number },
          "perk2Var1": { type: Number },
          "perk2Var2": { type: Number },
          "perk2Var3": { type: Number },
          "perk3": { type: Number },
          "perk3Var1": { type: Number },
          "perk3Var2": { type: Number },
          "perk3Var3": { type: Number },
          "perk4": { type: Number },
          "perk4Var1": { type: Number },
          "perk4Var2": { type: Number },
          "perk4Var3": { type: Number },
          "perk5": { type: Number },
          "perk5Var1": { type: Number },
          "perk5Var2": { type: Number },
          "perk5Var3": { type: Number },
          "perkPrimaryStyle": { type: Number },
          "perkSubStyle": { type: Number },
          "statPerk0": { type: Number },
          "statPerk1": { type: Number },
          "statPerk2": { type: Number }
        },
        // "timeline": {
        //   "participantId": { type: Number },
        //   "creepsPerMinDeltas": {
        //     "10-20": 3.2,
        //     "0-10": 5.3,
        //     "20-30": 2.0999999999999996
        //   },
        //   "xpPerMinDeltas": {
        //     "10-20": 520.1,
        //     "0-10": 381.29999999999995,
        //     "20-30": 482.09999999999997
        //   },
        //   "goldPerMinDeltas": {
        //     "10-20": 486.20000000000005,
        //     "0-10": 276,
        //     "20-30": 471.6
        //   },
        //   "csDiffPerMinDeltas": {
        //     "10-20": 0.9000000000000001,
        //     "0-10": 0.4999999999999998,
        //     "20-30": -1.5000000000000002
        //   },
        //   "xpDiffPerMinDeltas": {
        //     "10-20": 229.40000000000003,
        //     "0-10": -0.8000000000000114,
        //     "20-30": -27.500000000000057
        //   },
        //   "damageTakenPerMinDeltas": {
        //     "10-20": 1285.7,
        //     "0-10": 538,
        //     "20-30": 2024
        //   },
        //   "damageTakenDiffPerMinDeltas": {
        //     "10-20": 72.80000000000001,
        //     "0-10": 91.50000000000006,
        //     "20-30": 531.9
        //   },
        //   "role": "SOLO",
        //   "lane": "MIDDLE"
        // }
      },{
        "participantId": { type: Number },
        "teamId": { type: Number },
        "championId": { type: Number },
        "spell1Id": { type: Number },
        "spell2Id": { type: Number },
        "stats": {
          "participantId": { type: Number },
          "win": { type: Boolean },
          "item0": { type: Number },
          "item1": { type: Number },
          "item2": { type: Number },
          "item3": { type: Number },
          "item4": { type: Number },
          "item5": { type: Number },
          "item6": { type: Number },
          "kills": { type: Number },
          "deaths": { type: Number },
          "assists": { type: Number },
          "largestKillingSpree": { type: Number },
          "largestMultiKill": { type: Number },
          "killingSprees": { type: Number },
          "longestTimeSpentLiving": { type: Number },
          "doubleKills": { type: Number },
          "tripleKills": { type: Number },
          "quadraKills": { type: Number },
          "pentaKills": { type: Number },
          "unrealKills": { type: Number },
          "totalDamageDealt": { type: Number },
          "magicDamageDealt": { type: Number },
          "physicalDamageDealt": { type: Number },
          "trueDamageDealt": { type: Number },
          "largestCriticalStrike": { type: Number },
          "totalDamageDealtToChampions": { type: Number },
          "magicDamageDealtToChampions": { type: Number },
          "physicalDamageDealtToChampions": { type: Number },
          "trueDamageDealtToChampions": { type: Number },
          "totalHeal": { type: Number },
          "totalUnitsHealed": { type: Number },
          "damageSelfMitigated": { type: Number },
          "damageDealtToObjectives": { type: Number },
          "damageDealtToTurrets": { type: Number },
          "visionScore": { type: Number },
          "timeCCingOthers": { type: Number },
          "totalDamageTaken": { type: Number },
          "magicalDamageTaken": { type: Number },
          "physicalDamageTaken": { type: Number },
          "trueDamageTaken": { type: Number },
          "goldEarned": { type: Number },
          "goldSpent": { type: Number },
          "turretKills": { type: Number },
          "inhibitorKills": { type: Number },
          "totalMinionsKilled": { type: Number },
          "neutralMinionsKilled": { type: Number },
          "neutralMinionsKilledTeamJungle": { type: Number },
          "neutralMinionsKilledEnemyJungle": { type: Number },
          "totalTimeCrowdControlDealt": { type: Number },
          "champLevel": { type: Number },
          "visionWardsBoughtInGame": { type: Number },
          "sightWardsBoughtInGame": { type: Number },
          "wardsPlaced": { type: Number },
          "wardsKilled": { type: Number },
          "firstBloodKill": { type: Boolean },
          "firstBloodAssist": { type: Boolean },
          "firstTowerKill": { type: Boolean },
          "firstTowerAssist": { type: Boolean },
          "firstInhibitorKill": { type: Boolean },
          "firstInhibitorAssist": { type: Boolean },
          "combatPlayerScore": { type: Number },
          "objectivePlayerScore": { type: Number },
          "totalPlayerScore": { type: Number },
          "totalScoreRank": { type: Number },
          "playerScore0": { type: Number },
          "playerScore1": { type: Number },
          "playerScore2": { type: Number },
          "playerScore3": { type: Number },
          "playerScore4": { type: Number },
          "playerScore5": { type: Number },
          "playerScore6": { type: Number },
          "playerScore7": { type: Number },
          "playerScore8": { type: Number },
          "playerScore9": { type: Number },
          "perk0": { type: Number },
          "perk0Var1": { type: Number },
          "perk0Var2": { type: Number },
          "perk0Var3": { type: Number },
          "perk1": { type: Number },
          "perk1Var1": { type: Number },
          "perk1Var2": { type: Number },
          "perk1Var3": { type: Number },
          "perk2": { type: Number },
          "perk2Var1": { type: Number },
          "perk2Var2": { type: Number },
          "perk2Var3": { type: Number },
          "perk3": { type: Number },
          "perk3Var1": { type: Number },
          "perk3Var2": { type: Number },
          "perk3Var3": { type: Number },
          "perk4": { type: Number },
          "perk4Var1": { type: Number },
          "perk4Var2": { type: Number },
          "perk4Var3": { type: Number },
          "perk5": { type: Number },
          "perk5Var1": { type: Number },
          "perk5Var2": { type: Number },
          "perk5Var3": { type: Number },
          "perkPrimaryStyle": { type: Number },
          "perkSubStyle": { type: Number },
          "statPerk0": { type: Number },
          "statPerk1": { type: Number },
          "statPerk2": { type: Number }
        },
        // "timeline": {
        //   "participantId": { type: Number },
        //   "creepsPerMinDeltas": {
        //     "10-20": 3.2,
        //     "0-10": 5.3,
        //     "20-30": 2.0999999999999996
        //   },
        //   "xpPerMinDeltas": {
        //     "10-20": 520.1,
        //     "0-10": 381.29999999999995,
        //     "20-30": 482.09999999999997
        //   },
        //   "goldPerMinDeltas": {
        //     "10-20": 486.20000000000005,
        //     "0-10": 276,
        //     "20-30": 471.6
        //   },
        //   "csDiffPerMinDeltas": {
        //     "10-20": 0.9000000000000001,
        //     "0-10": 0.4999999999999998,
        //     "20-30": -1.5000000000000002
        //   },
        //   "xpDiffPerMinDeltas": {
        //     "10-20": 229.40000000000003,
        //     "0-10": -0.8000000000000114,
        //     "20-30": -27.500000000000057
        //   },
        //   "damageTakenPerMinDeltas": {
        //     "10-20": 1285.7,
        //     "0-10": 538,
        //     "20-30": 2024
        //   },
        //   "damageTakenDiffPerMinDeltas": {
        //     "10-20": 72.80000000000001,
        //     "0-10": 91.50000000000006,
        //     "20-30": 531.9
        //   },
        //   "role": "SOLO",
        //   "lane": "MIDDLE"
        // }
      },{
        "participantId": { type: Number },
        "teamId": { type: Number },
        "championId": { type: Number },
        "spell1Id": { type: Number },
        "spell2Id": { type: Number },
        "stats": {
          "participantId": { type: Number },
          "win": { type: Boolean },
          "item0": { type: Number },
          "item1": { type: Number },
          "item2": { type: Number },
          "item3": { type: Number },
          "item4": { type: Number },
          "item5": { type: Number },
          "item6": { type: Number },
          "kills": { type: Number },
          "deaths": { type: Number },
          "assists": { type: Number },
          "largestKillingSpree": { type: Number },
          "largestMultiKill": { type: Number },
          "killingSprees": { type: Number },
          "longestTimeSpentLiving": { type: Number },
          "doubleKills": { type: Number },
          "tripleKills": { type: Number },
          "quadraKills": { type: Number },
          "pentaKills": { type: Number },
          "unrealKills": { type: Number },
          "totalDamageDealt": { type: Number },
          "magicDamageDealt": { type: Number },
          "physicalDamageDealt": { type: Number },
          "trueDamageDealt": { type: Number },
          "largestCriticalStrike": { type: Number },
          "totalDamageDealtToChampions": { type: Number },
          "magicDamageDealtToChampions": { type: Number },
          "physicalDamageDealtToChampions": { type: Number },
          "trueDamageDealtToChampions": { type: Number },
          "totalHeal": { type: Number },
          "totalUnitsHealed": { type: Number },
          "damageSelfMitigated": { type: Number },
          "damageDealtToObjectives": { type: Number },
          "damageDealtToTurrets": { type: Number },
          "visionScore": { type: Number },
          "timeCCingOthers": { type: Number },
          "totalDamageTaken": { type: Number },
          "magicalDamageTaken": { type: Number },
          "physicalDamageTaken": { type: Number },
          "trueDamageTaken": { type: Number },
          "goldEarned": { type: Number },
          "goldSpent": { type: Number },
          "turretKills": { type: Number },
          "inhibitorKills": { type: Number },
          "totalMinionsKilled": { type: Number },
          "neutralMinionsKilled": { type: Number },
          "neutralMinionsKilledTeamJungle": { type: Number },
          "neutralMinionsKilledEnemyJungle": { type: Number },
          "totalTimeCrowdControlDealt": { type: Number },
          "champLevel": { type: Number },
          "visionWardsBoughtInGame": { type: Number },
          "sightWardsBoughtInGame": { type: Number },
          "wardsPlaced": { type: Number },
          "wardsKilled": { type: Number },
          "firstBloodKill": { type: Boolean },
          "firstBloodAssist": { type: Boolean },
          "firstTowerKill": { type: Boolean },
          "firstTowerAssist": { type: Boolean },
          "firstInhibitorKill": { type: Boolean },
          "firstInhibitorAssist": { type: Boolean },
          "combatPlayerScore": { type: Number },
          "objectivePlayerScore": { type: Number },
          "totalPlayerScore": { type: Number },
          "totalScoreRank": { type: Number },
          "playerScore0": { type: Number },
          "playerScore1": { type: Number },
          "playerScore2": { type: Number },
          "playerScore3": { type: Number },
          "playerScore4": { type: Number },
          "playerScore5": { type: Number },
          "playerScore6": { type: Number },
          "playerScore7": { type: Number },
          "playerScore8": { type: Number },
          "playerScore9": { type: Number },
          "perk0": { type: Number },
          "perk0Var1": { type: Number },
          "perk0Var2": { type: Number },
          "perk0Var3": { type: Number },
          "perk1": { type: Number },
          "perk1Var1": { type: Number },
          "perk1Var2": { type: Number },
          "perk1Var3": { type: Number },
          "perk2": { type: Number },
          "perk2Var1": { type: Number },
          "perk2Var2": { type: Number },
          "perk2Var3": { type: Number },
          "perk3": { type: Number },
          "perk3Var1": { type: Number },
          "perk3Var2": { type: Number },
          "perk3Var3": { type: Number },
          "perk4": { type: Number },
          "perk4Var1": { type: Number },
          "perk4Var2": { type: Number },
          "perk4Var3": { type: Number },
          "perk5": { type: Number },
          "perk5Var1": { type: Number },
          "perk5Var2": { type: Number },
          "perk5Var3": { type: Number },
          "perkPrimaryStyle": { type: Number },
          "perkSubStyle": { type: Number },
          "statPerk0": { type: Number },
          "statPerk1": { type: Number },
          "statPerk2": { type: Number }
        },
        // "timeline": {
        //   "participantId": { type: Number },
        //   "creepsPerMinDeltas": {
        //     "10-20": 3.2,
        //     "0-10": 5.3,
        //     "20-30": 2.0999999999999996
        //   },
        //   "xpPerMinDeltas": {
        //     "10-20": 520.1,
        //     "0-10": 381.29999999999995,
        //     "20-30": 482.09999999999997
        //   },
        //   "goldPerMinDeltas": {
        //     "10-20": 486.20000000000005,
        //     "0-10": 276,
        //     "20-30": 471.6
        //   },
        //   "csDiffPerMinDeltas": {
        //     "10-20": 0.9000000000000001,
        //     "0-10": 0.4999999999999998,
        //     "20-30": -1.5000000000000002
        //   },
        //   "xpDiffPerMinDeltas": {
        //     "10-20": 229.40000000000003,
        //     "0-10": -0.8000000000000114,
        //     "20-30": -27.500000000000057
        //   },
        //   "damageTakenPerMinDeltas": {
        //     "10-20": 1285.7,
        //     "0-10": 538,
        //     "20-30": 2024
        //   },
        //   "damageTakenDiffPerMinDeltas": {
        //     "10-20": 72.80000000000001,
        //     "0-10": 91.50000000000006,
        //     "20-30": 531.9
        //   },
        //   "role": "SOLO",
        //   "lane": "MIDDLE"
        // }
      },{
        "participantId": { type: Number },
        "teamId": { type: Number },
        "championId": { type: Number },
        "spell1Id": { type: Number },
        "spell2Id": { type: Number },
        "stats": {
          "participantId": { type: Number },
          "win": { type: Boolean },
          "item0": { type: Number },
          "item1": { type: Number },
          "item2": { type: Number },
          "item3": { type: Number },
          "item4": { type: Number },
          "item5": { type: Number },
          "item6": { type: Number },
          "kills": { type: Number },
          "deaths": { type: Number },
          "assists": { type: Number },
          "largestKillingSpree": { type: Number },
          "largestMultiKill": { type: Number },
          "killingSprees": { type: Number },
          "longestTimeSpentLiving": { type: Number },
          "doubleKills": { type: Number },
          "tripleKills": { type: Number },
          "quadraKills": { type: Number },
          "pentaKills": { type: Number },
          "unrealKills": { type: Number },
          "totalDamageDealt": { type: Number },
          "magicDamageDealt": { type: Number },
          "physicalDamageDealt": { type: Number },
          "trueDamageDealt": { type: Number },
          "largestCriticalStrike": { type: Number },
          "totalDamageDealtToChampions": { type: Number },
          "magicDamageDealtToChampions": { type: Number },
          "physicalDamageDealtToChampions": { type: Number },
          "trueDamageDealtToChampions": { type: Number },
          "totalHeal": { type: Number },
          "totalUnitsHealed": { type: Number },
          "damageSelfMitigated": { type: Number },
          "damageDealtToObjectives": { type: Number },
          "damageDealtToTurrets": { type: Number },
          "visionScore": { type: Number },
          "timeCCingOthers": { type: Number },
          "totalDamageTaken": { type: Number },
          "magicalDamageTaken": { type: Number },
          "physicalDamageTaken": { type: Number },
          "trueDamageTaken": { type: Number },
          "goldEarned": { type: Number },
          "goldSpent": { type: Number },
          "turretKills": { type: Number },
          "inhibitorKills": { type: Number },
          "totalMinionsKilled": { type: Number },
          "neutralMinionsKilled": { type: Number },
          "neutralMinionsKilledTeamJungle": { type: Number },
          "neutralMinionsKilledEnemyJungle": { type: Number },
          "totalTimeCrowdControlDealt": { type: Number },
          "champLevel": { type: Number },
          "visionWardsBoughtInGame": { type: Number },
          "sightWardsBoughtInGame": { type: Number },
          "wardsPlaced": { type: Number },
          "wardsKilled": { type: Number },
          "firstBloodKill": { type: Boolean },
          "firstBloodAssist": { type: Boolean },
          "firstTowerKill": { type: Boolean },
          "firstTowerAssist": { type: Boolean },
          "firstInhibitorKill": { type: Boolean },
          "firstInhibitorAssist": { type: Boolean },
          "combatPlayerScore": { type: Number },
          "objectivePlayerScore": { type: Number },
          "totalPlayerScore": { type: Number },
          "totalScoreRank": { type: Number },
          "playerScore0": { type: Number },
          "playerScore1": { type: Number },
          "playerScore2": { type: Number },
          "playerScore3": { type: Number },
          "playerScore4": { type: Number },
          "playerScore5": { type: Number },
          "playerScore6": { type: Number },
          "playerScore7": { type: Number },
          "playerScore8": { type: Number },
          "playerScore9": { type: Number },
          "perk0": { type: Number },
          "perk0Var1": { type: Number },
          "perk0Var2": { type: Number },
          "perk0Var3": { type: Number },
          "perk1": { type: Number },
          "perk1Var1": { type: Number },
          "perk1Var2": { type: Number },
          "perk1Var3": { type: Number },
          "perk2": { type: Number },
          "perk2Var1": { type: Number },
          "perk2Var2": { type: Number },
          "perk2Var3": { type: Number },
          "perk3": { type: Number },
          "perk3Var1": { type: Number },
          "perk3Var2": { type: Number },
          "perk3Var3": { type: Number },
          "perk4": { type: Number },
          "perk4Var1": { type: Number },
          "perk4Var2": { type: Number },
          "perk4Var3": { type: Number },
          "perk5": { type: Number },
          "perk5Var1": { type: Number },
          "perk5Var2": { type: Number },
          "perk5Var3": { type: Number },
          "perkPrimaryStyle": { type: Number },
          "perkSubStyle": { type: Number },
          "statPerk0": { type: Number },
          "statPerk1": { type: Number },
          "statPerk2": { type: Number }
        },
        // "timeline": {
        //   "participantId": { type: Number },
        //   "creepsPerMinDeltas": {
        //     "10-20": 3.2,
        //     "0-10": 5.3,
        //     "20-30": 2.0999999999999996
        //   },
        //   "xpPerMinDeltas": {
        //     "10-20": 520.1,
        //     "0-10": 381.29999999999995,
        //     "20-30": 482.09999999999997
        //   },
        //   "goldPerMinDeltas": {
        //     "10-20": 486.20000000000005,
        //     "0-10": 276,
        //     "20-30": 471.6
        //   },
        //   "csDiffPerMinDeltas": {
        //     "10-20": 0.9000000000000001,
        //     "0-10": 0.4999999999999998,
        //     "20-30": -1.5000000000000002
        //   },
        //   "xpDiffPerMinDeltas": {
        //     "10-20": 229.40000000000003,
        //     "0-10": -0.8000000000000114,
        //     "20-30": -27.500000000000057
        //   },
        //   "damageTakenPerMinDeltas": {
        //     "10-20": 1285.7,
        //     "0-10": 538,
        //     "20-30": 2024
        //   },
        //   "damageTakenDiffPerMinDeltas": {
        //     "10-20": 72.80000000000001,
        //     "0-10": 91.50000000000006,
        //     "20-30": 531.9
        //   },
        //   "role": "SOLO",
        //   "lane": "MIDDLE"
        // }
      }],
    // participantIdentities: [{

    // }]
});

const MatchDetails = mongoose.model("MatchDetails", detailsSchema);

module.exports = MatchDetails;
